<a href="https://colab.research.google.com/github/memetics19/WIDS2020/blob/master/Wids2020.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import xgboost as xgb
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.model_selection import train_test_split


data = pd.read_csv('data.csv')

In [0]:
data=data.dropna(axis=0)

In [0]:
x=data.drop(['encounter_id','height','weight','hospital_death','patient_id','hospital_id'],axis=1)
y=data['hospital_death']

In [25]:
X=data.iloc[:,3:].values
print(X)
Y=data.iloc[:].values
print(Y)

[[67.         28.14629137  0.         ...  0.          0.
   1.        ]
 [63.         30.70657029  1.         ...  0.          0.
   0.        ]
 [42.         27.92975528  0.         ...  0.          0.
   1.        ]
 ...
 [53.         39.93688461  0.         ...  0.          0.
   1.        ]
 [69.         22.11126871  1.         ...  0.          0.
   1.        ]
 [64.         36.0008906   0.         ...  0.          0.
   0.        ]]
[[8.04430e+04 9.93000e+03 8.90000e+01 ... 0.00000e+00 0.00000e+00
  1.00000e+00]
 [1.11879e+05 3.19760e+04 8.90000e+01 ... 0.00000e+00 0.00000e+00
  0.00000e+00]
 [1.09281e+05 1.20846e+05 8.90000e+01 ... 0.00000e+00 0.00000e+00
  1.00000e+00]
 ...
 [1.24931e+05 3.76030e+04 1.89000e+02 ... 0.00000e+00 0.00000e+00
  1.00000e+00]
 [9.25850e+04 3.87680e+04 1.33000e+02 ... 0.00000e+00 0.00000e+00
  1.00000e+00]
 [1.26740e+05 1.08681e+05 1.33000e+02 ... 0.00000e+00 0.00000e+00
  0.00000e+00]]

In [26]:
data.tail()

       encounter_id  patient_id  ...  apache_2_bodysystem_UD  hospital_death
45428          2672      119722  ...                     0.0             1.0
49874         25790      114947  ...                     0.0             1.0
50649        124931       37603  ...                     0.0             1.0
51742         92585       38768  ...                     0.0             1.0
52032        126740      108681  ...                     0.0             0.0

[5 rows x 244 columns]

In [0]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [28]:
model=xgb.XGBClassifier()
model=model.fit(x_test,y_test)
model=model.fit(x_train,y_train)
print(model)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)